name: travvel
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  sizer: ^3.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^1.1.1

  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  dio: ^5.4.0
  fluttertoast: ^9.0.0
  fl_chart: ^1.1.0
  url_launcher: ^6.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.5.3
  flutter_slidable: ^4.0.3

  path_provider: ^2.1.2
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_app_logo.png"
